### ISSUE TITLE
Peer to Peer code review (Week 5 - day 5)

### ISSUE THREAD

**Issue by zmekonnen251** [zmekonnen251/Tibeb-FrontEnd-Bootcamp#2]
- Please put your comments that you see in my project. Thanks you for your constructive feedback and comments.

**Comment by Mutalenic** [comment]
Job well done so far-the project will look better if you fix the logo on the about page in the mobile version.

**Comment by mnekx** [comment]
The less/more button could have been hidden in the desktop version so as to stick to the design as much as possible Consider the screenshot below:
![image](https://user-images.githubusercontent.com/22321030/152489332-610df6cd-d88f-4838-bc19-275206c7a885.png)
Otherwise, job well done. Kudos 💯

**Comment by i-max-xi** [comment]
Great work with everything. I’m impressed.
It would also be very nice nice to add transitions to the “show and hide” of the menu
Once again great job 👍

**Comment by zmekonnen251** [comment]
Thanks, guys for your constructive feedback. I accepted all your comments I will implement them and make changes accordingly.
